### ISSUE TITLE
Can't build tokenizer - OOM after 110 GB RAM

### ISSUE THREAD

**Issue by TinoDidriksen** [giellalt/lang-rus#20]
Given `./configure --without-forrest --with-hfst --enable-tokenisers --without-xfst --enable-reversed-intersect --enable-spellers --enable-hfst-mobile-speller --enable-alignment --disable-minimised-spellers --enable-syntax --enable-analysers --enable-generators --enable-apertium --enable-grammarchecker --with-backend-format=openfst-tropical --enable-dicts --enable-oahpa --enable-morpher --disable-hfst-desktop-spellers`

The step `/usr/bin/hfst-pmatch2fst < tokeniser-disamb-gt-desc.pmscript > tokeniser-disamb-gt-desc.pmhfst.tmp` eats all available RAM and is eventually killed.

Happens on both Linux (128 GB RAM) and Mac m1 (16 GB RAM).

**Comment by flammie** [comment]
Trying with --verbose it seems to happen when compiling the morphology, and only with openfst backend. I haven't debugged it much further but it seems that lexicon.hfst in lang-rus has negative weights which could definitely cause infinite loops, perhaps temporary workaround would be to compile unweighted version with foma backend.
